package com.banka1.verificationService.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import lombok.Getter;
import lombok.Setter;

/**
 * Data Transfer Object (DTO) for requesting verification code validation.
 *
 * Encapsulates the session identifier and user-provided code for verification.
 * The code must match a 6-digit pattern (generated by the service and sent via email).
 * All fields are validated upon deserialization.
 */
@Getter
@Setter
public class ValidateRequest {
    /**
     * The ID of the verification session to validate against.
     * Must refer to an existing session in the database.
     * Required and non-null.
     */
    @NotNull(message = "sessionId is required.")
    private Long sessionId;

    /**
     * The verification code provided by the user.
     * Must be exactly 6 digits (numeric only).
     * Matches the code sent to the client's email address.
     * Required and non-empty.
     */
    @NotBlank(message = "code is required.")
    @Pattern(regexp = "^\\d{6}$", message = "code must be a 6-digit number.")
    private String code;
}
