package com.banka1.verificationService.model.entity;

import com.banka1.verificationService.model.enums.OperationType;
import com.banka1.verificationService.model.enums.VerificationStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity representing a verification session in the database.
 *
 * Stores an HMAC-SHA256 hashed OTP code, session metadata, and state information
 * for two-factor authentication (2FA) operations. Each session is uniquely identified
 * by the combination of clientId, operationType, and relatedEntityId, with a lifecycle
 * controlled by its status and expiration time.
 *
 * A typical session flow:
 * <ol>
 *   <li>Created with status PENDING and a 5-minute expiration time</li>
 *   <li>User provides code within expiration window</li>
 *   <li>Status transitions to VERIFIED on match or CANCELLED after 3 failed attempts</li>
 *   <li>Status transitions to EXPIRED if current time passes expiresAt</li>
 * </ol>
 *
 * @see VerificationStatus
 * @see OperationType
 */
@Entity
@Table(name = "verification_sessions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class VerificationSession {

    /**
     * Unique identifier for this verification session, auto-generated by the database.
     * Primary key.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The ID of the client requesting verification.
     * Used to enforce authorization (client can only verify their own sessions)
     * and to query sessions by client.
     * Non-nullable.
     */
    @Column(nullable = false)
    private Long clientId;

    /**
     * Base64-encoded HMAC-SHA256 hash of the one-time password code.
     * The actual plain-text code is never stored; only the hash is persisted
     * in the database for security reasons.
     * Non-nullable.
     */
    @Column(nullable = false)
    private String code;

    /**
     * The type of operation requiring verification (e.g., PAYMENT, TRANSFER).
     * Used to categorize and qualify verification sessions.
     * Non-nullable.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private OperationType operationType;

    /**
     * The ID of the entity associated with this verification session (e.g., transaction ID, request ID).
     * Combined with clientId and operationType to uniquely identify a session
     * and prevent duplicate concurrent verifications for the same operation.
     * Non-nullable.
     */
    @Column(nullable = false)
    private String relatedEntityId;

    /**
     * Timestamp when this session was created.
     * Used for auditing and calculating session age.
     * Non-nullable.
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when this session expires.
     * Typically set to 5 minutes after creation. If the current time passes this
     * timestamp, the session should be transitioned to EXPIRED status.
     * Non-nullable.
     */
    @Column(nullable = false)
    private LocalDateTime expiresAt;

    /**
     * Counter for failed validation attempts.
     * Incremented on each invalid code submission. The session is automatically
     * cancelled when this counter reaches 3.
     * Non-nullable, defaults to 0.
     */
    @Column(nullable = false)
    private int attemptCount;

    /**
     * Current state of the verification session.
     * Transitions: PENDING → VERIFIED/EXPIRED/CANCELLED
     * Non-nullable.
     *
     * @see VerificationStatus
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private VerificationStatus status;
}
